/**
 * In-app defaults (used before fetch / offline). Mirror these as Remote Config
 * parameters in Firebase Console — same keys, string values (JSON for objects).
 */
import type { FeatureFlags, LocaleCode, TranslationTree } from "./types";

/** All Remote Config keys must be strings; encode objects with JSON.stringify */
export const REMOTE_CONFIG_DEFAULTS: Record<string, string> = {
  default_locale: "en",
  supported_locales: JSON.stringify(["en", "ur", "ar"] satisfies LocaleCode[]),

  feature_flags: JSON.stringify({
    ayatSection: true,
    hadithSection: true,
    statsV2: false,
    installPrompt: true,
    remoteTheming: true,
  } satisfies FeatureFlags),

  /** Nested: locale → key → string */
  i18n_strings: JSON.stringify({
    en: {
      "app.title": "Tasbeeh Flow",
      "splash.tagline": "Dhikr with calm — count, reflect, return.",
      "splash.continue": "Continue",
      "splash.loading": "One moment…",
      "home.crashlyticsTest": "Test Crashlytics",
      "home.crashlyticsTestHint": "Sends a non-fatal test error to Analytics (GA4 exception).",
      "home.firestoreTitle": "Firestore · test",
      "home.firestoreLoading": "Loading collection…",
      "home.firestoreEmpty": "No documents in `test`.",
      "home.firestoreUnavailable": "Firebase not configured (no Firestore client).",
      "home.firestoreName": "name",
      "home.firestoreError": "Could not load Firestore.",
      "home.asmaTitle": "Asma-ul-Husna",
      "home.asmaNoKey": "Add VITE_ISLAMIC_API_KEY in .env.local (IslamicAPI).",
      "home.asmaLoading": "Loading names…",
      "home.asmaError": "Could not load Asma-ul-Husna.",
      "home.asmaAttribution": "Data: IslamicAPI",
      "home.asmaStatusNoKey": "IslamicAPI: no key — add VITE_ISLAMIC_API_KEY to .env.local",
      "home.asmaStatusKeyOk": "IslamicAPI: key loaded from .env",
      "home.asmaEmpty": "API returned an empty list.",
      "nav.home": "Home",
      "nav.add": "Add",
      "nav.stats": "Stats",
      "settings.remote.refresh": "Refresh config",
      "settings.appearance.title": "Appearance",
      "settings.appearance.theme": "App Theme",
      "settings.appearance.themeHint": "Select a mood that suits your zikr",
      "settings.experience.title": "Experience",
      "settings.experience.haptics": "Haptic Feedback",
      "settings.experience.hapticsHint": "Vibrate when you tap to count",
      "settings.experience.reset": "Reset at Midnight",
      "settings.experience.resetHint": "Start your counts fresh each day",
      "settings.remind.title": "Daily Remembrance",
      "settings.remind.daily": "Daily Reminder",
      "settings.remind.dailyHint": "Gentle nudge to find your peace",
      "settings.sync.title": "Cloud & Sync",
      "settings.sync.status": "Sync Status",
      "settings.sync.now": "Sync Now",
      "settings.account.title": "Account",
      "settings.account.signInCta": "Sign in or create account",
      "settings.account.publicName": "Public name (emails & UI)",
      "settings.account.publicNameHint":
        "Set VITE_PUBLIC_APP_NAME in .env.local and use the same “Public-facing name” in Firebase Console so auth emails match your app.",
      "auth.completing": "Completing sign-in…",
      "auth.title": "Sign in",
      "auth.subtitle":
        "Continue with Google, email & password, or a one-time email link. New here? Choose Register.",
      "auth.dividerOr": "or",
      "auth.sectionPassword": "Email & password",
      "auth.signedInTitle": "Signed in",
      "auth.signedInHint":
        "To see sign-in, register, or forgot password again, sign out below. This page is also linked from Settings → Account.",
      "auth.signOut": "Sign out",
      "auth.backHome": "Back to home",
      "auth.unavailableTitle": "Sign-in unavailable",
      "auth.unavailableHint": "Add Firebase web config to .env.local (see .env.example).",
      "auth.googleSection": "Google",
      "auth.signInGoogle": "Continue with Google",
      "auth.modeSignIn": "Sign in",
      "auth.modeRegister": "Register",
      "auth.email": "Email",
      "auth.password": "Password",
      "auth.submitRegister": "Create account",
      "auth.submitSignIn": "Sign in with password",
      "auth.forgotPassword": "Forgot password?",
      "auth.resetSent": "If an account exists for that email, check your inbox for a reset link.",
      "auth.magicTitle": "Email link (passwordless)",
      "auth.magicHint": "We will email you a sign-in link. Use the same device you request from, or confirm your email when prompted.",
      "auth.sendMagicLink": "Send sign-in link",
      "auth.magicSent": "Check your inbox for the link.",
    },
    ur: {
      "app.title": "تسبیح",
      "splash.tagline": "ذکرِ خداوندی — سکون سے، ایک ایک مرتبہ۔",
      "splash.continue": "آگے بڑھیں",
      "splash.loading": "ایک لمحہ…",
      "home.crashlyticsTest": "کرشلائٹکس ٹیسٹ",
      "home.crashlyticsTestHint": "غیر فاتل ٹیسٹ ایرر Analytics بھیجتا ہے۔",
      "home.firestoreTitle": "Firestore · test",
      "home.firestoreLoading": "لوڈ ہو رہا ہے…",
      "home.firestoreEmpty": "`test` میں کوئی دستاویز نہیں۔",
      "home.firestoreUnavailable": "Firebase کنفیگ نہیں۔",
      "home.firestoreName": "نام",
      "home.firestoreError": "Firestore لوڈ نہیں ہوا۔",
      "home.asmaTitle": "اسماء الحسنی",
      "home.asmaNoKey": ".env.local میں VITE_ISLAMIC_API_KEY شامل کریں (IslamicAPI)۔",
      "home.asmaLoading": "نام لوڈ ہو رہے ہیں…",
      "home.asmaError": "اسماء الحسنی لوڈ نہیں ہو سکے۔",
      "home.asmaAttribution": "ڈیٹا: IslamicAPI",
      "home.asmaStatusNoKey": "IslamicAPI: کوئی کلید نہیں — .env.local میں VITE_ISLAMIC_API_KEY",
      "home.asmaStatusKeyOk": "IslamicAPI: کلید لوڈ ہو گئی",
      "home.asmaEmpty": "API نے خالی فہرست بھیجی۔",
      "nav.home": "ہوم",
      "nav.add": "شامل کریں",
      "nav.stats": "اعداد",
      "nav.settings": "ترتیبات",
      "settings.remote.title": "کلاؤڈ اور ریموٹ کنفیگ",
      "settings.remote.flags": "فیچر فلیگز",
      "settings.remote.locale": "زبان",
      "settings.remote.refresh": "کنفیگ تازہ کریں",
      "settings.account.title": "اکاؤنٹ",
      "settings.account.signInCta": "سائن ان یا نیا اکاؤنٹ",
      "settings.account.publicName": "عوامی نام (ای میلز اور UI)",
      "settings.account.publicNameHint":
        ".env.local میں VITE_PUBLIC_APP_NAME سیٹ کریں اور Firebase کنسول میں وہی “Public-facing name” استعمال کریں۔",
      "auth.completing": "سائن ان مکمل ہو رہا ہے…",
      "auth.title": "سائن ان",
      "auth.subtitle":
        "گوگل، ای میل و پاس ورڈ، یا ایک بار کا ای میل لنک۔ نئے صارف: رجسٹر۔",
      "auth.dividerOr": "یا",
      "auth.sectionPassword": "ای میل اور پاس ورڈ",
      "auth.signedInTitle": "سائن ان",
      "auth.signedInHint":
        "دوبارہ سائن ان یا رجسٹر دیکھنے کے لیے سائن آؤٹ کریں۔ ترتیبات → اکاؤنٹ سے بھی یہ صفحہ کھولیں۔",
      "auth.signOut": "سائن آؤٹ",
      "auth.backHome": "ہوم پر واپس",
      "auth.unavailableTitle": "سائن ان دستیاب نہیں",
      "auth.unavailableHint": "Firebase کنفیگ .env.local میں شامل کریں۔",
      "auth.googleSection": "گوگل",
      "auth.signInGoogle": "گوگل سے جاری رکھیں",
      "auth.modeSignIn": "سائن ان",
      "auth.modeRegister": "رجسٹر",
      "auth.email": "ای میل",
      "auth.password": "پاس ورڈ",
      "auth.submitRegister": "اکاؤنٹ بنائیں",
      "auth.submitSignIn": "پاس ورڈ سے سائن ان",
      "auth.forgotPassword": "پاس ورڈ بھول گئے؟",
      "auth.resetSent": "اگر اس ای میل پر اکاؤنٹ ہے تو ری سیٹ لنک بھیج دیا گیا ہے۔",
      "auth.magicTitle": "ای میل لنک (بغیر پاس ورڈ)",
      "auth.magicHint": "ہم آپ کو سائن ان لنک بھیجیں گے۔ ممکن ہو تو اسی ڈیوائس سے درخواست کریں۔",
      "auth.sendMagicLink": "لنک بھیجیں",
      "auth.magicSent": "اپنا ان باکس چیک کریں۔",
    },
    ar: {
      "app.title": "تسبيح",
      "splash.tagline": "ذكر هادئ — عدًّا تلويحًا.",
      "splash.continue": "متابعة",
      "splash.loading": "لحظة…",
      "home.crashlyticsTest": "اختبار Crashlytics",
      "home.crashlyticsTestHint": "يرسل خطأ تجريبيًا غير فادح إلى Analytics.",
      "home.firestoreTitle": "Firestore · test",
      "home.firestoreLoading": "جارٍ التحميل…",
      "home.firestoreEmpty": "لا مستندات في `test`.",
      "home.firestoreUnavailable": "Firebase غير مهيأ.",
      "home.firestoreName": "الاسم",
      "home.firestoreError": "تعذر تحميل Firestore.",
      "home.asmaTitle": "أسماء الله الحسنى",
      "home.asmaNoKey": "أضف VITE_ISLAMIC_API_KEY في .env.local (IslamicAPI).",
      "home.asmaLoading": "جارٍ تحميل الأسماء…",
      "home.asmaError": "تعذر تحميل الأسماء الحسنى.",
      "home.asmaAttribution": "البيانات: IslamicAPI",
      "home.asmaStatusNoKey": "IslamicAPI: لا يوجد مفتاح — أضف VITE_ISLAMIC_API_KEY",
      "home.asmaStatusKeyOk": "IslamicAPI: تم تحميل المفتاح",
      "home.asmaEmpty": "قائمة الأسماء فارغة من الـ API.",
      "nav.home": "الرئيسية",
      "nav.add": "إضافة",
      "nav.stats": "إحصائيات",
      "nav.settings": "الإعدادات",
      "settings.remote.title": "السحابة والإعداد البعيد",
      "settings.remote.flags": "ميزات التبديل",
      "settings.remote.locale": "اللغة",
      "settings.remote.refresh": "تحديث الإعدادات",
      "settings.account.title": "الحساب",
      "settings.account.signInCta": "تسجيل الدخول أو إنشاء حساب",
      "settings.account.publicName": "الاسم العام (البريد والواجهة)",
      "settings.account.publicNameHint":
        "عيّن VITE_PUBLIC_APP_NAME في .env.local واستخدم نفس «الاسم الظاهر للجميع» في Firebase.",
      "auth.completing": "جارٍ إكمال تسجيل الدخول…",
      "auth.title": "تسجيل الدخول",
      "auth.subtitle":
        "المتابعة عبر Google أو البريد وكلمة المرور أو رابط لمرة واحدة. جديد؟ اختر تسجيل.",
      "auth.dividerOr": "أو",
      "auth.sectionPassword": "البريد وكلمة المرور",
      "auth.signedInTitle": "تم تسجيل الدخول",
      "auth.signedInHint":
        "لإظهار تسجيل الدخول أو التسجيل أو استعادة كلمة المرور، سجّل الخروج أدناه. الصفحة مرتبطة من الإعدادات → الحساب.",
      "auth.signOut": "تسجيل الخروج",
      "auth.backHome": "العودة للرئيسية",
      "auth.unavailableTitle": "تسجيل الدخول غير متاح",
      "auth.unavailableHint": "أضف إعداد Firebase إلى .env.local.",
      "auth.googleSection": "Google",
      "auth.signInGoogle": "المتابعة باستخدام Google",
      "auth.modeSignIn": "دخول",
      "auth.modeRegister": "تسجيل",
      "auth.email": "البريد",
      "auth.password": "كلمة المرور",
      "auth.submitRegister": "إنشاء حساب",
      "auth.submitSignIn": "دخول بكلمة المرور",
      "auth.forgotPassword": "نسيت كلمة المرور؟",
      "auth.resetSent": "إذا وُجد حساب لهذا البريد، أرسلنا رابط إعادة التعيين.",
      "auth.magicTitle": "رابط البريد (بدون كلمة مرور)",
      "auth.magicHint": "سنرسل رابط تسجيل. استخدم نفس الجهاز إن أمكن.",
      "auth.sendMagicLink": "إرسال الرابط",
      "auth.magicSent": "تحقق من بريدك الوارد.",
    },
  } satisfies TranslationTree),
};

export const LOCALE_STORAGE_KEY = "tasbeeh_locale";
